language: go
go:
- 1.14
services:
- docker
git:
  depth: 150
os:
- linux
- osx
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: bpv+ZtPnIH6jzYOefJLNW1bI8Eu337baqIf9tinPFKMr5JSISKQUUY8+NvnNnAVIHbMhik/7aCF1iFED0OIJFe5t4d21uNU3pGmKN9wADI9vCfEsKzEwvDW8wuVpjZY7IAdIwH7J0Np5Imz9nZ62A9y5aNoKzAe2ksaa1kic7j1jHHKJoqV5S+nhTCBisAdEcUNq2EJNU0q2zQLJdr/rDZ3zEhNo78QHnsD+13JFMbJ6lGCtXFUXTnyTSAGQjAw2zyxNYZNxlsqDgN4aFJ6a3hj1IYdZOI5/spD8UF9fSfEVvTmyeKFxLoHKZL0QEKy9TSPV7h7EOOki+IcLgXlZBZyFjfRIKjFGc0XnLQdRIgBAkNsMQqGw6/jy08AbDBN8HV13u9263137NGL/tZpx/x2COBk0BaNx5cjV2EUbRRys+4gaNI/Y4qCwTnAEVs/tbU9ocSYxmfjyF2iqnbVChq3COstc0M0EqYW0UtR2JfENgkAryhOHUQKZNph/AJOOpU7gp5V6A48hk/wsngW7DWmHc45ZwAFeqXKfiIlGtZQr+WgkPj2l5gRjzK+aknSPlzLnxBuSfj9kwaQzX6iLvHgnfXogjFk5aMH4b16k1fdqAVeYKGOTM0AvNzwLpGBj3AlPPPls1Fgzg3fgRWe8nrC9YWPjMiwncCKdV9jj9/0=
  - secure: "jcccP9RPPe1A8YdefUpmMqqWvpDB4FN1a9lbwXnDeg/Ud3zPlInmdjvqT19MDGbHG11rCiLMuu5kSwdOlBE0kucNsEpTNwYDVfP2J5BibUvKZoRrqzz21NCKiqCQAS88xs+8uYPwJsKvdH4XB17XlvHCegsh4z7yiioU0+3al7VcEbQCRFY0LiSmOoFV0SPKIWxvPo8GGomPXWnTR6C/Eo7prsxb5caC1F5tYctILk3bkGZ+5G2TunzoTp7I4cVx4FKG6KdcKB6PPhb8xqRtOpLu27CtpuCCCljmF3MNG8stiZQVtok6qydNe3+i1oes70iZ7i3HnyQMs6BfcaRSXpK+Xt6EimU+Cmi0q0yBvqBhLX52/7sSgpkSqiH8fcuCosm3p9qPEua1MsbQD/6UiqJ6OFcRXsbOtna+FzY2FixtBNGXyeHsVUuI/tliZL09R8eWtjVa6lDBt0Wl2uCuErozXesFiJwqzw0i75sJZyvHIhu3EuYcZ8gJ+0XzP6KnktDLcTfxeUt0Fbgg0QTK+YfzyMcJvMimWR7XKOojf2noOX/8OlsxzzGAZm1k3YqlT5ir6ANwhtIkan4ZHuybkncuPXtUYphcJXEctd5EPKE9SbgRePF7h9VadVd8ac7xGfUsN9Qs5zlEqF/XyKrXZI9ibN692KcXL77eXK2blSU="
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install node && nvm use node
  - pushd web && npm install && popd
  - make setup
script:
- make test
before_deploy:
- openssl aes-256-cbc -K $encrypted_ee4987f84485_key -iv $encrypted_ee4987f84485_iv
  -in equinox.tar.enc -out equinox.tar -d
- tar xvf equinox.tar
deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
      condition:
        - "$TRAVIS_OS_NAME = linux"
        - "-z $TRAVIS_TAG"
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
